### ISSUE TITLE
在阿里云centos 7.4的机器上出现编译错误

### ISSUE THREAD

**Issue by qiangmzsx** [b3log/pipe#110]
# npm run build

> pipe-admin@1.0.0 build /home/work/code/golang/src/github.com/b3log/pipe/console
> nuxt build

/home/work/code/golang/src/github.com/b3log/pipe/console/node_modules/nuxt/lib/core/module.js:14
  async ready() {
        ^^^^^

SyntaxError: Unexpected identifier
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/work/code/golang/src/github.com/b3log/pipe/console/node_modules/nuxt/lib/core/index.js:2:16)

**Comment by 88250** [comment]
请使用最新版的 node。
